vich_uploader:
    db_driver: orm

    mappings:
       imagesEducPluto:
           uri_prefix: '%educpluto_images%'
           upload_destination: '%kernel.project_dir%/public%educpluto_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
